Repository directus/sdk-js, pull requests merged in 2019-07, with the labels that each got.

#81 Add ability to get files
  src/index.js
Labels: enhancement

#82 Add security policy
  SECURITY.md
Labels: enhancement

#84 Add codeowenrs file for auto-review settings
  .github/CODEOWNERS
Labels: enhancement

#85 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#83 Add frontend issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01-bug-report.md
  .github/ISSUE_TEMPLATE/02-docs-report.md
  .github/ISSUE_TEMPLATE/02-feature-request.md
Labels: enhancement

#86 Introduce overrideHeaders parameter for the uploadFiles method
  dist/directus-sdk.js
  dist/directus-sdk.umd.js
  dist/directus-sdk.umd.min.js
  dist/directus-sdk.umd.min.js.map
  package-lock.json
  package.json
  src/index.js
  test/methods/files.js
Labels: enhancement

#87 fix/ping
  dist/directus-sdk.js
  dist/directus-sdk.umd.js
  dist/directus-sdk.umd.min.js
  dist/directus-sdk.umd.min.js.map
  package.json
  src/index.js
Labels: bug

#88 chore: use workflow from ts feature branch for auto-publish
  .github/main.workflow
  package-lock.json
  package.json
  test/authentication.js
  test/general.js
  test/methods/files.js
  test/methods/listing-preferences.js
  test/payload.js
Labels: enhancement, optimization

#89 Security Patch #091619
  package-lock.json
  package.json
  test/methods/utils.js
Labels: bug, enhancement

#93 Buildchain refactoring to tsc->rollup->uglifyjs (adds ESModule support)
  .eslintignore
  .gitignore
  config/utils.js
  config/webpack.config.base.js
  config/webpack.config.client-development.js
  config/webpack.config.client-production.js
  config/webpack.config.server.js
  dist/directus-sdk.js
  dist/directus-sdk.umd.js
  dist/directus-sdk.umd.min.js
  dist/directus-sdk.umd.min.js.map
  dist/umd/directus-sdk.js
  dist/umd/directus-sdk.js.map
  dist/umd/directus-sdk.min.js
  dist/umd/directus-sdk.min.js.map
  package-lock.json
  package.json
  src/API.ts
  src/Authentication.ts
  src/Configuration.ts
  src/SDK.ts
  tsconfig.json
  webpack.config.js
Labels: enhancement

#97 Update docs and recipes
  README.md
  recipes/README.md
  recipes/frameworks/Angular.md
  recipes/frameworks/NGRX.md
  recipes/frameworks/RXJS.md
  recipes/frameworks/React.md
  recipes/frameworks/Redux.md
  recipes/frameworks/Vue.md
Labels: enhancement
